use variable instead

diff --git a/.github/workflows/daily-dev-bump.yaml b/.github/workflows/daily-dev-bump.yaml
--- a/.github/workflows/daily-dev-bump.yaml
+++ b/.github/workflows/daily-dev-bump.yaml
@@ -40,14 +40,15 @@ jobs:
 
         CURRENT_VERSION=$(dart tool/update_version.dart current-version)
         if ! echo "$CURRENT_VERSION" | grep -q " -dev\.[0-9]$"; then
-          echo ""
-          echo "::error ,title=Cannot Bump A Release Version::Doing \
-          a Dev bump on a release version is not supported. \
-          Upgrade the current patch, minor, or major version then do a \
-          dev prerelease in order to continue"
-          exit 1;
-        fi
-        
+          ERROR_DESCRIPTION="Doing \
+        a Dev bump on a release version is not supported. \
+        Upgrade the current patch, minor, or major version then do a \
+        dev prerelease in order to continue"
+
+      echo "::error ,title=Cannot Bump A Release Version::$ERROR_DESCRIPTION"          
+      exit 1;
+    fi
+    
         # Get the commit message
         COMMIT_MESSAGE=$(dart tool/update_version.dart auto --dry-run --type dev)
         echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
